analyzer:
  exclude:
    - build/**
    - .dart_tool/**
  errors:
    deprecated_member_use: ignore
    invalid_use_of_visible_for_testing_member: ignore
    invalid_use_of_protected_member: ignore
    prefer_const_constructors: ignore
    prefer_final_locals: ignore
    unused_element_parameter: ignore
linter:
  rules:
    prefer_const_constructors: false
    prefer_final_locals: false
