name: shinra_core
publish_to: 'none'
version: 1.0.0+36
environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  shared_preferences: ^2.5.3
  path_provider: ^2.1.5
  provider: ^6.1.5+1
  image: ^4.2.0
  audioplayers: ^6.7.1
  ffmpeg_kit_flutter_new: ^4.6.0
  google_fonts: ^6.2.1
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/characters/
    - assets/animations/
    - assets/expressions/
    - assets/effects/
    - assets/effects/sprites/
    - assets/audio/
    - assets/library/
    - assets/starter_characters/
