class ShinraAsset { const ShinraAsset(this.category, this.path, this.name); final String category; final String path; final String name; }

const shinraAssets = <ShinraAsset>[
  ShinraAsset('Visages', 'assets/library/faces.png', 'faces'),
  ShinraAsset('Visages', 'assets/library/faces_cell_01.png', 'faces 01'),
  ShinraAsset('Visages', 'assets/library/faces_cell_02.png', 'faces 02'),
  ShinraAsset('Visages', 'assets/library/faces_cell_03.png', 'faces 03'),
  ShinraAsset('Visages', 'assets/library/faces_cell_04.png', 'faces 04'),
  ShinraAsset('Visages', 'assets/library/faces_cell_05.png', 'faces 05'),
  ShinraAsset('Visages', 'assets/library/faces_cell_06.png', 'faces 06'),
  ShinraAsset('Visages', 'assets/library/faces_cell_07.png', 'faces 07'),
  ShinraAsset('Visages', 'assets/library/faces_cell_08.png', 'faces 08'),
  ShinraAsset('Visages', 'assets/library/faces_cell_09.png', 'faces 09'),
  ShinraAsset('Visages', 'assets/library/faces_cell_10.png', 'faces 10'),
  ShinraAsset('Visages', 'assets/library/faces_cell_11.png', 'faces 11'),
  ShinraAsset('Visages', 'assets/library/faces_cell_12.png', 'faces 12'),
  ShinraAsset('Visages', 'assets/library/faces_cell_13.png', 'faces 13'),
  ShinraAsset('Visages', 'assets/library/faces_cell_14.png', 'faces 14'),
  ShinraAsset('Visages', 'assets/library/faces_cell_15.png', 'faces 15'),
  ShinraAsset('Visages', 'assets/library/faces_cell_16.png', 'faces 16'),
  ShinraAsset('Visages', 'assets/library/faces_cell_17.png', 'faces 17'),
  ShinraAsset('Visages', 'assets/library/faces_cell_18.png', 'faces 18'),
  ShinraAsset('Visages', 'assets/library/faces_cell_19.png', 'faces 19'),
  ShinraAsset('Visages', 'assets/library/faces_cell_20.png', 'faces 20'),
  ShinraAsset('Visages', 'assets/library/faces_cell_21.png', 'faces 21'),
  ShinraAsset('Visages', 'assets/library/faces_cell_22.png', 'faces 22'),
  ShinraAsset('Visages', 'assets/library/faces_cell_23.png', 'faces 23'),
  ShinraAsset('Visages', 'assets/library/faces_cell_24.png', 'faces 24'),
  ShinraAsset('Visages', 'assets/library/faces_cell_25.png', 'faces 25'),
  ShinraAsset('Yeux', 'assets/library/eyes.png', 'eyes'),
  ShinraAsset('Yeux', 'assets/library/eyes_cell_01.png', 'eyes 01'),
  ShinraAsset('Yeux', 'assets/library/eyes_cell_02.png', 'eyes 02'),
  ShinraAsset('Yeux', 'assets/library/eyes_cell_03.png', 'eyes 03'),
  ShinraAsset('Yeux', 'assets/library/eyes_cell_04.png', 'eyes 04'),
  ShinraAsset('Yeux', 'assets/library/eyes_cell_05.png', 'eyes 05'),
  ShinraAsset('Yeux', 'assets/library/eyes_cell_06.png', 'eyes 06'),
  ShinraAsset('Yeux', 'assets/library/eyes_cell_07.png', 'eyes 07'),
  ShinraAsset('Yeux', 'assets/library/eyes_cell_08.png', 'eyes 08'),
  ShinraAsset('Yeux', 'assets/library/eyes_cell_09.png', 'eyes 09'),
  ShinraAsset('Yeux', 'assets/library/eyes_cell_10.png', 'eyes 10'),
  ShinraAsset('Yeux', 'assets/library/eyes_cell_11.png', 'eyes 11'),
  ShinraAsset('Yeux', 'assets/library/eyes_cell_12.png', 'eyes 12'),
  ShinraAsset('Yeux', 'assets/library/eyes_cell_13.png', 'eyes 13'),
  ShinraAsset('Yeux', 'assets/library/eyes_cell_14.png', 'eyes 14'),
  ShinraAsset('Yeux', 'assets/library/eyes_cell_15.png', 'eyes 15'),
  ShinraAsset('Yeux', 'assets/library/eyes_cell_16.png', 'eyes 16'),
  ShinraAsset('Yeux', 'assets/library/eyes_cell_17.png', 'eyes 17'),
  ShinraAsset('Yeux', 'assets/library/eyes_cell_18.png', 'eyes 18'),
  ShinraAsset('Yeux', 'assets/library/eyes_cell_19.png', 'eyes 19'),
  ShinraAsset('Yeux', 'assets/library/eyes_cell_20.png', 'eyes 20'),
  ShinraAsset('Yeux', 'assets/library/eyes_cell_21.png', 'eyes 21'),
  ShinraAsset('Yeux', 'assets/library/eyes_cell_22.png', 'eyes 22'),
  ShinraAsset('Yeux', 'assets/library/eyes_cell_23.png', 'eyes 23'),
  ShinraAsset('Yeux', 'assets/library/eyes_cell_24.png', 'eyes 24'),
  ShinraAsset('Yeux', 'assets/library/eyes_cell_25.png', 'eyes 25'),
  ShinraAsset('Yeux', 'assets/library/eyes_cell_26.png', 'eyes 26'),
  ShinraAsset('Yeux', 'assets/library/eyes_cell_27.png', 'eyes 27'),
  ShinraAsset('Yeux', 'assets/library/eyes_cell_28.png', 'eyes 28'),
  ShinraAsset('Yeux', 'assets/library/eyes_cell_29.png', 'eyes 29'),
  ShinraAsset('Yeux', 'assets/library/eyes_cell_30.png', 'eyes 30'),
  ShinraAsset('Yeux', 'assets/library/eyes_cell_31.png', 'eyes 31'),
  ShinraAsset('Yeux', 'assets/library/eyes_cell_32.png', 'eyes 32'),
  ShinraAsset('Yeux', 'assets/library/eyes_cell_33.png', 'eyes 33'),
  ShinraAsset('Yeux', 'assets/library/eyes_cell_34.png', 'eyes 34'),
  ShinraAsset('Yeux', 'assets/library/eyes_cell_35.png', 'eyes 35'),
  ShinraAsset('Cheveux', 'assets/library/hair.png', 'hair'),
  ShinraAsset('Cheveux', 'assets/library/hair_cell_01.png', 'hair 01'),
  ShinraAsset('Cheveux', 'assets/library/hair_cell_02.png', 'hair 02'),
  ShinraAsset('Cheveux', 'assets/library/hair_cell_03.png', 'hair 03'),
  ShinraAsset('Cheveux', 'assets/library/hair_cell_04.png', 'hair 04'),
  ShinraAsset('Cheveux', 'assets/library/hair_cell_05.png', 'hair 05'),
  ShinraAsset('Cheveux', 'assets/library/hair_cell_06.png', 'hair 06'),
  ShinraAsset('Cheveux', 'assets/library/hair_cell_07.png', 'hair 07'),
  ShinraAsset('Cheveux', 'assets/library/hair_cell_08.png', 'hair 08'),
  ShinraAsset('Cheveux', 'assets/library/hair_cell_09.png', 'hair 09'),
  ShinraAsset('Cheveux', 'assets/library/hair_cell_10.png', 'hair 10'),
  ShinraAsset('Cheveux', 'assets/library/hair_cell_11.png', 'hair 11'),
  ShinraAsset('Cheveux', 'assets/library/hair_cell_12.png', 'hair 12'),
  ShinraAsset('Cheveux', 'assets/library/hair_cell_13.png', 'hair 13'),
  ShinraAsset('Cheveux', 'assets/library/hair_cell_14.png', 'hair 14'),
  ShinraAsset('Cheveux', 'assets/library/hair_cell_15.png', 'hair 15'),
  ShinraAsset('Cheveux', 'assets/library/hair_cell_16.png', 'hair 16'),
  ShinraAsset('Cheveux', 'assets/library/hair_cell_17.png', 'hair 17'),
  ShinraAsset('Cheveux', 'assets/library/hair_cell_18.png', 'hair 18'),
  ShinraAsset('Cheveux', 'assets/library/hair_cell_19.png', 'hair 19'),
  ShinraAsset('Cheveux', 'assets/library/hair_cell_20.png', 'hair 20'),
  ShinraAsset('Cheveux', 'assets/library/hair_cell_21.png', 'hair 21'),
  ShinraAsset('Cheveux', 'assets/library/hair_cell_22.png', 'hair 22'),
  ShinraAsset('Cheveux', 'assets/library/hair_cell_23.png', 'hair 23'),
  ShinraAsset('Cheveux', 'assets/library/hair_cell_24.png', 'hair 24'),
  ShinraAsset('Cheveux', 'assets/library/hair_cell_25.png', 'hair 25'),
  ShinraAsset('Cheveux', 'assets/library/hair_cell_26.png', 'hair 26'),
  ShinraAsset('Cheveux', 'assets/library/hair_cell_27.png', 'hair 27'),
  ShinraAsset('Cheveux', 'assets/library/hair_cell_28.png', 'hair 28'),
  ShinraAsset('Cheveux', 'assets/library/hair_cell_29.png', 'hair 29'),
  ShinraAsset('Cheveux', 'assets/library/hair_cell_30.png', 'hair 30'),
  ShinraAsset('Cheveux', 'assets/library/hair_cell_31.png', 'hair 31'),
  ShinraAsset('Cheveux', 'assets/library/hair_cell_32.png', 'hair 32'),
  ShinraAsset('Cheveux', 'assets/library/hair_cell_33.png', 'hair 33'),
  ShinraAsset('Cheveux', 'assets/library/hair_cell_34.png', 'hair 34'),
  ShinraAsset('Cheveux', 'assets/library/hair_cell_35.png', 'hair 35'),
  ShinraAsset('Cheveux', 'assets/library/hair_cell_36.png', 'hair 36'),
  ShinraAsset('Barbes', 'assets/library/beards.png', 'beards'),
  ShinraAsset('Expressions', 'assets/library/expressions.png', 'expressions'),
  ShinraAsset('Expressions', 'assets/library/expressions_cell_01.png', 'expressions 01'),
  ShinraAsset('Expressions', 'assets/library/expressions_cell_02.png', 'expressions 02'),
  ShinraAsset('Expressions', 'assets/library/expressions_cell_03.png', 'expressions 03'),
  ShinraAsset('Expressions', 'assets/library/expressions_cell_04.png', 'expressions 04'),
  ShinraAsset('Expressions', 'assets/library/expressions_cell_05.png', 'expressions 05'),
  ShinraAsset('Expressions', 'assets/library/expressions_cell_06.png', 'expressions 06'),
  ShinraAsset('Expressions', 'assets/library/expressions_cell_07.png', 'expressions 07'),
  ShinraAsset('Expressions', 'assets/library/expressions_cell_08.png', 'expressions 08'),
  ShinraAsset('Expressions', 'assets/library/expressions_cell_09.png', 'expressions 09'),
  ShinraAsset('Expressions', 'assets/library/expressions_cell_10.png', 'expressions 10'),
  ShinraAsset('Expressions', 'assets/library/expressions_cell_11.png', 'expressions 11'),
  ShinraAsset('Expressions', 'assets/library/expressions_cell_12.png', 'expressions 12'),
  ShinraAsset('Expressions', 'assets/library/expressions_cell_13.png', 'expressions 13'),
  ShinraAsset('Expressions', 'assets/library/expressions_cell_14.png', 'expressions 14'),
  ShinraAsset('Expressions', 'assets/library/expressions_cell_15.png', 'expressions 15'),
  ShinraAsset('Expressions', 'assets/library/expressions_cell_16.png', 'expressions 16'),
  ShinraAsset('Expressions', 'assets/library/expressions_cell_17.png', 'expressions 17'),
  ShinraAsset('Expressions', 'assets/library/expressions_cell_18.png', 'expressions 18'),
  ShinraAsset('Expressions', 'assets/library/expressions_cell_19.png', 'expressions 19'),
  ShinraAsset('Expressions', 'assets/library/expressions_cell_20.png', 'expressions 20'),
  ShinraAsset('Expressions', 'assets/library/expressions_cell_21.png', 'expressions 21'),
  ShinraAsset('Expressions', 'assets/library/expressions_cell_22.png', 'expressions 22'),
  ShinraAsset('Expressions', 'assets/library/expressions_cell_23.png', 'expressions 23'),
  ShinraAsset('Expressions', 'assets/library/expressions_cell_24.png', 'expressions 24'),
  ShinraAsset('Expressions', 'assets/library/expressions_cell_25.png', 'expressions 25'),
  ShinraAsset('Expressions', 'assets/library/expressions_cell_26.png', 'expressions 26'),
  ShinraAsset('Expressions', 'assets/library/expressions_cell_27.png', 'expressions 27'),
  ShinraAsset('Expressions', 'assets/library/expressions_cell_28.png', 'expressions 28'),
  ShinraAsset('Expressions', 'assets/library/expressions_cell_29.png', 'expressions 29'),
  ShinraAsset('Expressions', 'assets/library/expressions_cell_30.png', 'expressions 30'),
  ShinraAsset('Corps', 'assets/library/bodies.png', 'bodies'),
  ShinraAsset('Corps', 'assets/library/bodies_cell_01.png', 'bodies 01'),
  ShinraAsset('Corps', 'assets/library/bodies_cell_02.png', 'bodies 02'),
  ShinraAsset('Corps', 'assets/library/bodies_cell_03.png', 'bodies 03'),
  ShinraAsset('Corps', 'assets/library/bodies_cell_04.png', 'bodies 04'),
  ShinraAsset('Corps', 'assets/library/bodies_cell_05.png', 'bodies 05'),
  ShinraAsset('Corps', 'assets/library/bodies_cell_06.png', 'bodies 06'),
  ShinraAsset('Corps', 'assets/library/bodies_cell_07.png', 'bodies 07'),
  ShinraAsset('Corps', 'assets/library/bodies_cell_08.png', 'bodies 08'),
  ShinraAsset('Corps', 'assets/library/bodies_cell_09.png', 'bodies 09'),
  ShinraAsset('Corps', 'assets/library/bodies_cell_10.png', 'bodies 10'),
  ShinraAsset('Corps', 'assets/library/bodies_cell_11.png', 'bodies 11'),
  ShinraAsset('Corps', 'assets/library/bodies_cell_12.png', 'bodies 12'),
  ShinraAsset('Corps', 'assets/library/bodies_cell_13.png', 'bodies 13'),
  ShinraAsset('Corps', 'assets/library/bodies_cell_14.png', 'bodies 14'),
  ShinraAsset('Corps', 'assets/library/bodies_cell_15.png', 'bodies 15'),
  ShinraAsset('Corps', 'assets/library/bodies_cell_16.png', 'bodies 16'),
  ShinraAsset('Corps', 'assets/library/bodies_cell_17.png', 'bodies 17'),
  ShinraAsset('Corps', 'assets/library/bodies_cell_18.png', 'bodies 18'),
  ShinraAsset('Corps', 'assets/library/bodies_cell_19.png', 'bodies 19'),
  ShinraAsset('Corps', 'assets/library/bodies_cell_20.png', 'bodies 20'),
  ShinraAsset('Vêtements', 'assets/library/clothes.png', 'clothes'),
  ShinraAsset('Vêtements', 'assets/library/clothes_cell_01.png', 'clothes 01'),
  ShinraAsset('Vêtements', 'assets/library/clothes_cell_02.png', 'clothes 02'),
  ShinraAsset('Vêtements', 'assets/library/clothes_cell_03.png', 'clothes 03'),
  ShinraAsset('Vêtements', 'assets/library/clothes_cell_04.png', 'clothes 04'),
  ShinraAsset('Vêtements', 'assets/library/clothes_cell_05.png', 'clothes 05'),
  ShinraAsset('Vêtements', 'assets/library/clothes_cell_06.png', 'clothes 06'),
  ShinraAsset('Vêtements', 'assets/library/clothes_cell_07.png', 'clothes 07'),
  ShinraAsset('Vêtements', 'assets/library/clothes_cell_08.png', 'clothes 08'),
  ShinraAsset('Vêtements', 'assets/library/clothes_cell_09.png', 'clothes 09'),
  ShinraAsset('Vêtements', 'assets/library/clothes_cell_10.png', 'clothes 10'),
  ShinraAsset('Vêtements', 'assets/library/clothes_cell_11.png', 'clothes 11'),
  ShinraAsset('Vêtements', 'assets/library/clothes_cell_12.png', 'clothes 12'),
  ShinraAsset('Vêtements', 'assets/library/clothes_cell_13.png', 'clothes 13'),
  ShinraAsset('Vêtements', 'assets/library/clothes_cell_14.png', 'clothes 14'),
  ShinraAsset('Vêtements', 'assets/library/clothes_cell_15.png', 'clothes 15'),
  ShinraAsset('Vêtements', 'assets/library/clothes_cell_16.png', 'clothes 16'),
  ShinraAsset('Vêtements', 'assets/library/clothes_cell_17.png', 'clothes 17'),
  ShinraAsset('Vêtements', 'assets/library/clothes_cell_18.png', 'clothes 18'),
  ShinraAsset('Vêtements', 'assets/library/clothes_cell_19.png', 'clothes 19'),
  ShinraAsset('Vêtements', 'assets/library/clothes_cell_20.png', 'clothes 20'),
  ShinraAsset('Vêtements', 'assets/library/clothes_cell_21.png', 'clothes 21'),
  ShinraAsset('Vêtements', 'assets/library/clothes_cell_22.png', 'clothes 22'),
  ShinraAsset('Vêtements', 'assets/library/clothes_cell_23.png', 'clothes 23'),
  ShinraAsset('Vêtements', 'assets/library/clothes_cell_24.png', 'clothes 24'),
  ShinraAsset('Vêtements', 'assets/library/clothes_cell_25.png', 'clothes 25'),
  ShinraAsset('Vêtements', 'assets/library/clothes_cell_26.png', 'clothes 26'),
  ShinraAsset('Vêtements', 'assets/library/clothes_cell_27.png', 'clothes 27'),
  ShinraAsset('Vêtements', 'assets/library/clothes_cell_28.png', 'clothes 28'),
  ShinraAsset('Vêtements', 'assets/library/clothes_cell_29.png', 'clothes 29'),
  ShinraAsset('Vêtements', 'assets/library/clothes_cell_30.png', 'clothes 30'),
  ShinraAsset('Vêtements', 'assets/library/clothes_cell_31.png', 'clothes 31'),
  ShinraAsset('Vêtements', 'assets/library/clothes_cell_32.png', 'clothes 32'),
  ShinraAsset('Vêtements', 'assets/library/clothes_cell_33.png', 'clothes 33'),
  ShinraAsset('Vêtements', 'assets/library/clothes_cell_34.png', 'clothes 34'),
  ShinraAsset('Vêtements', 'assets/library/clothes_cell_35.png', 'clothes 35'),
  ShinraAsset('Vêtements', 'assets/library/clothes_cell_36.png', 'clothes 36'),
  ShinraAsset('Vêtements', 'assets/library/clothes_cell_37.png', 'clothes 37'),
  ShinraAsset('Vêtements', 'assets/library/clothes_cell_38.png', 'clothes 38'),
  ShinraAsset('Vêtements', 'assets/library/clothes_cell_39.png', 'clothes 39'),
  ShinraAsset('Vêtements', 'assets/library/clothes_cell_40.png', 'clothes 40'),
  ShinraAsset('Accessoires', 'assets/library/accessories.png', 'accessories'),
  ShinraAsset('Accessoires', 'assets/library/accessories_cell_01.png', 'accessories 01'),
  ShinraAsset('Accessoires', 'assets/library/accessories_cell_02.png', 'accessories 02'),
  ShinraAsset('Accessoires', 'assets/library/accessories_cell_03.png', 'accessories 03'),
  ShinraAsset('Accessoires', 'assets/library/accessories_cell_04.png', 'accessories 04'),
  ShinraAsset('Accessoires', 'assets/library/accessories_cell_05.png', 'accessories 05'),
  ShinraAsset('Accessoires', 'assets/library/accessories_cell_06.png', 'accessories 06'),
  ShinraAsset('Accessoires', 'assets/library/accessories_cell_07.png', 'accessories 07'),
  ShinraAsset('Accessoires', 'assets/library/accessories_cell_08.png', 'accessories 08'),
  ShinraAsset('Accessoires', 'assets/library/accessories_cell_09.png', 'accessories 09'),
  ShinraAsset('Accessoires', 'assets/library/accessories_cell_10.png', 'accessories 10'),
  ShinraAsset('Accessoires', 'assets/library/accessories_cell_11.png', 'accessories 11'),
  ShinraAsset('Accessoires', 'assets/library/accessories_cell_12.png', 'accessories 12'),
  ShinraAsset('Accessoires', 'assets/library/accessories_cell_13.png', 'accessories 13'),
  ShinraAsset('Accessoires', 'assets/library/accessories_cell_14.png', 'accessories 14'),
  ShinraAsset('Accessoires', 'assets/library/accessories_cell_15.png', 'accessories 15'),
  ShinraAsset('Accessoires', 'assets/library/accessories_cell_16.png', 'accessories 16'),
  ShinraAsset('Accessoires', 'assets/library/accessories_cell_17.png', 'accessories 17'),
  ShinraAsset('Accessoires', 'assets/library/accessories_cell_18.png', 'accessories 18'),
  ShinraAsset('Accessoires', 'assets/library/accessories_cell_19.png', 'accessories 19'),
  ShinraAsset('Accessoires', 'assets/library/accessories_cell_20.png', 'accessories 20'),
  ShinraAsset('Accessoires', 'assets/library/accessories_cell_21.png', 'accessories 21'),
  ShinraAsset('Accessoires', 'assets/library/accessories_cell_22.png', 'accessories 22'),
  ShinraAsset('Accessoires', 'assets/library/accessories_cell_23.png', 'accessories 23'),
  ShinraAsset('Accessoires', 'assets/library/accessories_cell_24.png', 'accessories 24'),
  ShinraAsset('Accessoires', 'assets/library/accessories_cell_25.png', 'accessories 25'),
  ShinraAsset('Accessoires', 'assets/library/accessories_cell_26.png', 'accessories 26'),
  ShinraAsset('Accessoires', 'assets/library/accessories_cell_27.png', 'accessories 27'),
  ShinraAsset('Accessoires', 'assets/library/accessories_cell_28.png', 'accessories 28'),
  ShinraAsset('Accessoires', 'assets/library/accessories_cell_29.png', 'accessories 29'),
  ShinraAsset('Accessoires', 'assets/library/accessories_cell_30.png', 'accessories 30'),
  ShinraAsset('Cheveux avancés', 'assets/library/hair_advanced.png', 'hair advanced'),
  ShinraAsset('Cheveux avancés', 'assets/library/hairadv_cell_01.png', 'hairadv 01'),
  ShinraAsset('Cheveux avancés', 'assets/library/hairadv_cell_02.png', 'hairadv 02'),
  ShinraAsset('Cheveux avancés', 'assets/library/hairadv_cell_03.png', 'hairadv 03'),
  ShinraAsset('Cheveux avancés', 'assets/library/hairadv_cell_04.png', 'hairadv 04'),
  ShinraAsset('Cheveux avancés', 'assets/library/hairadv_cell_05.png', 'hairadv 05'),
  ShinraAsset('Cheveux avancés', 'assets/library/hairadv_cell_06.png', 'hairadv 06'),
  ShinraAsset('Cheveux avancés', 'assets/library/hairadv_cell_07.png', 'hairadv 07'),
  ShinraAsset('Cheveux avancés', 'assets/library/hairadv_cell_08.png', 'hairadv 08'),
  ShinraAsset('Cheveux avancés', 'assets/library/hairadv_cell_09.png', 'hairadv 09'),
  ShinraAsset('Cheveux avancés', 'assets/library/hairadv_cell_10.png', 'hairadv 10'),
  ShinraAsset('Cheveux avancés', 'assets/library/hairadv_cell_11.png', 'hairadv 11'),
  ShinraAsset('Cheveux avancés', 'assets/library/hairadv_cell_12.png', 'hairadv 12'),
  ShinraAsset('Cheveux avancés', 'assets/library/hairadv_cell_13.png', 'hairadv 13'),
  ShinraAsset('Cheveux avancés', 'assets/library/hairadv_cell_14.png', 'hairadv 14'),
  ShinraAsset('Cheveux avancés', 'assets/library/hairadv_cell_15.png', 'hairadv 15'),
  ShinraAsset('Cheveux avancés', 'assets/library/hairadv_cell_16.png', 'hairadv 16'),
  ShinraAsset('Cheveux avancés', 'assets/library/hairadv_cell_17.png', 'hairadv 17'),
  ShinraAsset('Cheveux avancés', 'assets/library/hairadv_cell_18.png', 'hairadv 18'),
  ShinraAsset('Cheveux avancés', 'assets/library/hairadv_cell_19.png', 'hairadv 19'),
  ShinraAsset('Cheveux avancés', 'assets/library/hairadv_cell_20.png', 'hairadv 20'),
  ShinraAsset('Cheveux avancés', 'assets/library/hairadv_cell_21.png', 'hairadv 21'),
  ShinraAsset('Cheveux avancés', 'assets/library/hairadv_cell_22.png', 'hairadv 22'),
  ShinraAsset('Cheveux avancés', 'assets/library/hairadv_cell_23.png', 'hairadv 23'),
  ShinraAsset('Cheveux avancés', 'assets/library/hairadv_cell_24.png', 'hairadv 24'),
  ShinraAsset('Cheveux avancés', 'assets/library/hairadv_cell_25.png', 'hairadv 25'),
  ShinraAsset('Cheveux avancés', 'assets/library/hairadv_cell_26.png', 'hairadv 26'),
  ShinraAsset('Cheveux avancés', 'assets/library/hairadv_cell_27.png', 'hairadv 27'),
  ShinraAsset('Cheveux avancés', 'assets/library/hairadv_cell_28.png', 'hairadv 28'),
  ShinraAsset('Cheveux avancés', 'assets/library/hairadv_cell_29.png', 'hairadv 29'),
  ShinraAsset('Cheveux avancés', 'assets/library/hairadv_cell_30.png', 'hairadv 30'),
  ShinraAsset('Cheveux avancés', 'assets/library/hairadv_cell_31.png', 'hairadv 31'),
  ShinraAsset('Cheveux avancés', 'assets/library/hairadv_cell_32.png', 'hairadv 32'),
  ShinraAsset('Cheveux avancés', 'assets/library/hairadv_cell_33.png', 'hairadv 33'),
  ShinraAsset('Cheveux avancés', 'assets/library/hairadv_cell_34.png', 'hairadv 34'),
  ShinraAsset('Cheveux avancés', 'assets/library/hairadv_cell_35.png', 'hairadv 35'),
  ShinraAsset('Cheveux avancés', 'assets/library/hairadv_cell_36.png', 'hairadv 36'),
  ShinraAsset('Mains & pieds', 'assets/library/hands_cell_01.png', 'hands 01'),
  ShinraAsset('Mains & pieds', 'assets/library/hands_cell_02.png', 'hands 02'),
  ShinraAsset('Mains & pieds', 'assets/library/hands_cell_03.png', 'hands 03'),
  ShinraAsset('Mains & pieds', 'assets/library/hands_cell_04.png', 'hands 04'),
  ShinraAsset('Mains & pieds', 'assets/library/hands_cell_05.png', 'hands 05'),
  ShinraAsset('Mains & pieds', 'assets/library/hands_cell_06.png', 'hands 06'),
  ShinraAsset('Mains & pieds', 'assets/library/hands_cell_07.png', 'hands 07'),
  ShinraAsset('Mains & pieds', 'assets/library/hands_cell_08.png', 'hands 08'),
  ShinraAsset('Mains & pieds', 'assets/library/hands_cell_09.png', 'hands 09'),
  ShinraAsset('Mains & pieds', 'assets/library/hands_cell_10.png', 'hands 10'),
  ShinraAsset('Mains & pieds', 'assets/library/hands_cell_11.png', 'hands 11'),
  ShinraAsset('Mains & pieds', 'assets/library/hands_cell_12.png', 'hands 12'),
  ShinraAsset('Mains & pieds', 'assets/library/hands_cell_13.png', 'hands 13'),
  ShinraAsset('Mains & pieds', 'assets/library/hands_cell_14.png', 'hands 14'),
  ShinraAsset('Mains & pieds', 'assets/library/hands_cell_15.png', 'hands 15'),
  ShinraAsset('Mains & pieds', 'assets/library/hands_cell_16.png', 'hands 16'),
  ShinraAsset('Mains & pieds', 'assets/library/hands_cell_17.png', 'hands 17'),
  ShinraAsset('Mains & pieds', 'assets/library/hands_cell_18.png', 'hands 18'),
  ShinraAsset('Mains & pieds', 'assets/library/hands_cell_19.png', 'hands 19'),
  ShinraAsset('Mains & pieds', 'assets/library/hands_cell_20.png', 'hands 20'),
  ShinraAsset('Mains & pieds', 'assets/library/hands_cell_21.png', 'hands 21'),
  ShinraAsset('Mains & pieds', 'assets/library/hands_cell_22.png', 'hands 22'),
  ShinraAsset('Mains & pieds', 'assets/library/hands_cell_23.png', 'hands 23'),
  ShinraAsset('Mains & pieds', 'assets/library/hands_cell_24.png', 'hands 24'),
  ShinraAsset('Mains & pieds', 'assets/library/hands_cell_25.png', 'hands 25'),
  ShinraAsset('Mains & pieds', 'assets/library/hands_cell_26.png', 'hands 26'),
  ShinraAsset('Mains & pieds', 'assets/library/hands_cell_27.png', 'hands 27'),
  ShinraAsset('Mains & pieds', 'assets/library/hands_cell_28.png', 'hands 28'),
  ShinraAsset('Mains & pieds', 'assets/library/hands_cell_29.png', 'hands 29'),
  ShinraAsset('Mains & pieds', 'assets/library/hands_cell_30.png', 'hands 30'),
  ShinraAsset('Mains & pieds', 'assets/library/hands_feet.png', 'hands feet'),
  ShinraAsset('Armes', 'assets/library/weapons.png', 'weapons'),
  ShinraAsset('Armes', 'assets/library/weapons_cell_01.png', 'weapons 01'),
  ShinraAsset('Armes', 'assets/library/weapons_cell_02.png', 'weapons 02'),
  ShinraAsset('Armes', 'assets/library/weapons_cell_03.png', 'weapons 03'),
  ShinraAsset('Armes', 'assets/library/weapons_cell_04.png', 'weapons 04'),
  ShinraAsset('Armes', 'assets/library/weapons_cell_05.png', 'weapons 05'),
  ShinraAsset('Armes', 'assets/library/weapons_cell_06.png', 'weapons 06'),
  ShinraAsset('Armes', 'assets/library/weapons_cell_07.png', 'weapons 07'),
  ShinraAsset('Armes', 'assets/library/weapons_cell_08.png', 'weapons 08'),
  ShinraAsset('Armes', 'assets/library/weapons_cell_09.png', 'weapons 09'),
  ShinraAsset('Armes', 'assets/library/weapons_cell_10.png', 'weapons 10'),
  ShinraAsset('Armes', 'assets/library/weapons_cell_11.png', 'weapons 11'),
  ShinraAsset('Armes', 'assets/library/weapons_cell_12.png', 'weapons 12'),
  ShinraAsset('Armes', 'assets/library/weapons_cell_13.png', 'weapons 13'),
  ShinraAsset('Armes', 'assets/library/weapons_cell_14.png', 'weapons 14'),
  ShinraAsset('Armes', 'assets/library/weapons_cell_15.png', 'weapons 15'),
  ShinraAsset('Armes', 'assets/library/weapons_cell_16.png', 'weapons 16'),
  ShinraAsset('Armes', 'assets/library/weapons_cell_17.png', 'weapons 17'),
  ShinraAsset('Armes', 'assets/library/weapons_cell_18.png', 'weapons 18'),
  ShinraAsset('Armes', 'assets/library/weapons_cell_19.png', 'weapons 19'),
  ShinraAsset('Armes', 'assets/library/weapons_cell_20.png', 'weapons 20'),
  ShinraAsset('Armes', 'assets/library/weapons_cell_21.png', 'weapons 21'),
  ShinraAsset('Armes', 'assets/library/weapons_cell_22.png', 'weapons 22'),
  ShinraAsset('Armes', 'assets/library/weapons_cell_23.png', 'weapons 23'),
  ShinraAsset('Armes', 'assets/library/weapons_cell_24.png', 'weapons 24'),
  ShinraAsset('Armes', 'assets/library/weapons_cell_25.png', 'weapons 25'),
  ShinraAsset('Armes', 'assets/library/weapons_cell_26.png', 'weapons 26'),
  ShinraAsset('Armes', 'assets/library/weapons_cell_27.png', 'weapons 27'),
  ShinraAsset('Armes', 'assets/library/weapons_cell_28.png', 'weapons 28'),
  ShinraAsset('Effets', 'assets/library/fx.png', 'fx'),
  ShinraAsset('Effets', 'assets/library/fx_cell_01.png', 'fx 01'),
  ShinraAsset('Effets', 'assets/library/fx_cell_02.png', 'fx 02'),
  ShinraAsset('Effets', 'assets/library/fx_cell_03.png', 'fx 03'),
  ShinraAsset('Effets', 'assets/library/fx_cell_04.png', 'fx 04'),
  ShinraAsset('Effets', 'assets/library/fx_cell_05.png', 'fx 05'),
  ShinraAsset('Effets', 'assets/library/fx_cell_06.png', 'fx 06'),
  ShinraAsset('Effets', 'assets/library/fx_cell_07.png', 'fx 07'),
  ShinraAsset('Effets', 'assets/library/fx_cell_08.png', 'fx 08'),
  ShinraAsset('Effets', 'assets/library/fx_cell_09.png', 'fx 09'),
  ShinraAsset('Effets', 'assets/library/fx_cell_10.png', 'fx 10'),
  ShinraAsset('Effets', 'assets/library/fx_cell_11.png', 'fx 11'),
  ShinraAsset('Effets', 'assets/library/fx_cell_12.png', 'fx 12'),
  ShinraAsset('Effets', 'assets/library/fx_cell_13.png', 'fx 13'),
  ShinraAsset('Effets', 'assets/library/fx_cell_14.png', 'fx 14'),
  ShinraAsset('Effets', 'assets/library/fx_cell_15.png', 'fx 15'),
  ShinraAsset('Effets', 'assets/library/fx_cell_16.png', 'fx 16'),
  ShinraAsset('Effets', 'assets/library/fx_cell_17.png', 'fx 17'),
  ShinraAsset('Effets', 'assets/library/fx_cell_18.png', 'fx 18'),
  ShinraAsset('Effets', 'assets/library/fx_cell_19.png', 'fx 19'),
  ShinraAsset('Effets', 'assets/library/fx_cell_20.png', 'fx 20'),
  ShinraAsset('Poses', 'assets/library/poses.png', 'poses'),
  ShinraAsset('Poses', 'assets/library/poses_cell_01.png', 'poses 01'),
  ShinraAsset('Poses', 'assets/library/poses_cell_02.png', 'poses 02'),
  ShinraAsset('Poses', 'assets/library/poses_cell_03.png', 'poses 03'),
  ShinraAsset('Poses', 'assets/library/poses_cell_04.png', 'poses 04'),
  ShinraAsset('Poses', 'assets/library/poses_cell_05.png', 'poses 05'),
  ShinraAsset('Poses', 'assets/library/poses_cell_06.png', 'poses 06'),
  ShinraAsset('Poses', 'assets/library/poses_cell_07.png', 'poses 07'),
  ShinraAsset('Poses', 'assets/library/poses_cell_08.png', 'poses 08'),
  ShinraAsset('Poses', 'assets/library/poses_cell_09.png', 'poses 09'),
  ShinraAsset('Poses', 'assets/library/poses_cell_10.png', 'poses 10'),
  ShinraAsset('Poses', 'assets/library/poses_cell_11.png', 'poses 11'),
  ShinraAsset('Poses', 'assets/library/poses_cell_12.png', 'poses 12'),
  ShinraAsset('Poses', 'assets/library/poses_cell_13.png', 'poses 13'),
  ShinraAsset('Poses', 'assets/library/poses_cell_14.png', 'poses 14'),
  ShinraAsset('Poses', 'assets/library/poses_cell_15.png', 'poses 15'),
  ShinraAsset('Poses', 'assets/library/poses_cell_16.png', 'poses 16'),
  ShinraAsset('Poses', 'assets/library/poses_cell_17.png', 'poses 17'),
  ShinraAsset('Poses', 'assets/library/poses_cell_18.png', 'poses 18'),
  ShinraAsset('Poses', 'assets/library/poses_cell_19.png', 'poses 19'),
  ShinraAsset('Poses', 'assets/library/poses_cell_20.png', 'poses 20'),
  ShinraAsset('Poses', 'assets/library/poses_cell_21.png', 'poses 21'),
  ShinraAsset('Poses', 'assets/library/poses_cell_22.png', 'poses 22'),
  ShinraAsset('Poses', 'assets/library/poses_cell_23.png', 'poses 23'),
  ShinraAsset('Poses', 'assets/library/poses_cell_24.png', 'poses 24'),
  ShinraAsset('Poses', 'assets/library/poses_cell_25.png', 'poses 25'),
  ShinraAsset('Poses', 'assets/library/poses_cell_26.png', 'poses 26'),
  ShinraAsset('Poses', 'assets/library/poses_cell_27.png', 'poses 27'),
  ShinraAsset('Poses', 'assets/library/poses_cell_28.png', 'poses 28'),
  ShinraAsset('Poses', 'assets/library/poses_cell_29.png', 'poses 29'),
  ShinraAsset('Poses', 'assets/library/poses_cell_30.png', 'poses 30'),
  ShinraAsset('Poses', 'assets/library/poses_cell_31.png', 'poses 31'),
  ShinraAsset('Poses', 'assets/library/poses_cell_32.png', 'poses 32'),
  ShinraAsset('Poses', 'assets/library/poses_cell_33.png', 'poses 33'),
  ShinraAsset('Poses', 'assets/library/poses_cell_34.png', 'poses 34'),
  ShinraAsset('Poses', 'assets/library/poses_cell_35.png', 'poses 35'),
  ShinraAsset('Poses', 'assets/library/poses_cell_36.png', 'poses 36'),
  ShinraAsset('Poses', 'assets/library/poses_cell_37.png', 'poses 37'),
  ShinraAsset('Poses', 'assets/library/poses_cell_38.png', 'poses 38'),
  ShinraAsset('Poses', 'assets/library/poses_cell_39.png', 'poses 39'),
  ShinraAsset('Poses', 'assets/library/poses_cell_40.png', 'poses 40'),
  ShinraAsset('Poses', 'assets/library/poses_cell_41.png', 'poses 41'),
  ShinraAsset('Poses', 'assets/library/poses_cell_42.png', 'poses 42'),
  ShinraAsset('Poses', 'assets/library/poses_cell_43.png', 'poses 43'),
  ShinraAsset('Poses', 'assets/library/poses_cell_44.png', 'poses 44'),
  ShinraAsset('Poses', 'assets/library/poses_cell_45.png', 'poses 45'),
  ShinraAsset('Poses', 'assets/library/poses_cell_46.png', 'poses 46'),
  ShinraAsset('Poses', 'assets/library/poses_cell_47.png', 'poses 47'),
  ShinraAsset('Poses', 'assets/library/poses_cell_48.png', 'poses 48'),
  ShinraAsset('Poses', 'assets/library/poses_cell_49.png', 'poses 49'),
  ShinraAsset('Poses', 'assets/library/poses_cell_50.png', 'poses 50'),
  ShinraAsset('Scènes', 'assets/library/scenes.png', 'scenes'),
  ShinraAsset('Scènes', 'assets/library/scenes_cell_01.png', 'scenes 01'),
  ShinraAsset('Scènes', 'assets/library/scenes_cell_02.png', 'scenes 02'),
  ShinraAsset('Scènes', 'assets/library/scenes_cell_03.png', 'scenes 03'),
  ShinraAsset('Scènes', 'assets/library/scenes_cell_04.png', 'scenes 04'),
  ShinraAsset('Scènes', 'assets/library/scenes_cell_05.png', 'scenes 05'),
  ShinraAsset('Scènes', 'assets/library/scenes_cell_06.png', 'scenes 06'),
  ShinraAsset('Scènes', 'assets/library/scenes_cell_07.png', 'scenes 07'),
  ShinraAsset('Scènes', 'assets/library/scenes_cell_08.png', 'scenes 08'),
  ShinraAsset('Scènes', 'assets/library/scenes_cell_09.png', 'scenes 09'),
  ShinraAsset('Scènes', 'assets/library/scenes_cell_10.png', 'scenes 10'),
  ShinraAsset('Scènes', 'assets/library/scenes_cell_11.png', 'scenes 11'),
  ShinraAsset('Scènes', 'assets/library/scenes_cell_12.png', 'scenes 12'),
  ShinraAsset('Scènes', 'assets/library/scenes_cell_13.png', 'scenes 13'),
  ShinraAsset('Scènes', 'assets/library/scenes_cell_14.png', 'scenes 14'),
  ShinraAsset('Scènes', 'assets/library/scenes_cell_15.png', 'scenes 15'),
  ShinraAsset('Scènes', 'assets/library/scenes_cell_16.png', 'scenes 16'),
  ShinraAsset('Scènes', 'assets/library/scenes_cell_17.png', 'scenes 17'),
  ShinraAsset('Scènes', 'assets/library/scenes_cell_18.png', 'scenes 18'),
  ShinraAsset('Scènes', 'assets/library/scenes_cell_19.png', 'scenes 19'),
  ShinraAsset('Scènes', 'assets/library/scenes_cell_20.png', 'scenes 20'),
  ShinraAsset('Scènes', 'assets/library/scenes_cell_21.png', 'scenes 21'),
  ShinraAsset('Scènes', 'assets/library/scenes_cell_22.png', 'scenes 22'),
  ShinraAsset('Scènes', 'assets/library/scenes_cell_23.png', 'scenes 23'),
  ShinraAsset('Scènes', 'assets/library/scenes_cell_24.png', 'scenes 24'),
  ShinraAsset('Scènes', 'assets/library/scenes_cell_25.png', 'scenes 25'),
  ShinraAsset('Environnements', 'assets/library/env_cell_01.png', 'env 01'),
  ShinraAsset('Environnements', 'assets/library/env_cell_02.png', 'env 02'),
  ShinraAsset('Environnements', 'assets/library/env_cell_03.png', 'env 03'),
  ShinraAsset('Environnements', 'assets/library/env_cell_04.png', 'env 04'),
  ShinraAsset('Environnements', 'assets/library/env_cell_05.png', 'env 05'),
  ShinraAsset('Environnements', 'assets/library/env_cell_06.png', 'env 06'),
  ShinraAsset('Environnements', 'assets/library/env_cell_07.png', 'env 07'),
  ShinraAsset('Environnements', 'assets/library/env_cell_08.png', 'env 08'),
  ShinraAsset('Environnements', 'assets/library/env_cell_09.png', 'env 09'),
  ShinraAsset('Environnements', 'assets/library/env_cell_10.png', 'env 10'),
  ShinraAsset('Environnements', 'assets/library/env_cell_11.png', 'env 11'),
  ShinraAsset('Environnements', 'assets/library/env_cell_12.png', 'env 12'),
  ShinraAsset('Environnements', 'assets/library/env_cell_13.png', 'env 13'),
  ShinraAsset('Environnements', 'assets/library/env_cell_14.png', 'env 14'),
  ShinraAsset('Environnements', 'assets/library/env_cell_15.png', 'env 15'),
  ShinraAsset('Environnements', 'assets/library/env_cell_16.png', 'env 16'),
  ShinraAsset('Environnements', 'assets/library/env_cell_17.png', 'env 17'),
  ShinraAsset('Environnements', 'assets/library/env_cell_18.png', 'env 18'),
  ShinraAsset('Environnements', 'assets/library/env_cell_19.png', 'env 19'),
  ShinraAsset('Environnements', 'assets/library/env_cell_20.png', 'env 20'),
  ShinraAsset('Environnements', 'assets/library/env_cell_21.png', 'env 21'),
  ShinraAsset('Environnements', 'assets/library/env_cell_22.png', 'env 22'),
  ShinraAsset('Environnements', 'assets/library/env_cell_23.png', 'env 23'),
  ShinraAsset('Environnements', 'assets/library/env_cell_24.png', 'env 24'),
  ShinraAsset('Environnements', 'assets/library/env_cell_25.png', 'env 25'),
  ShinraAsset('Environnements', 'assets/library/environments.png', 'environments'),
  ShinraAsset('Créatures', 'assets/library/creatures.png', 'creatures'),
  ShinraAsset('Créatures', 'assets/library/creatures_cell_01.png', 'creatures 01'),
  ShinraAsset('Créatures', 'assets/library/creatures_cell_02.png', 'creatures 02'),
  ShinraAsset('Créatures', 'assets/library/creatures_cell_03.png', 'creatures 03'),
  ShinraAsset('Créatures', 'assets/library/creatures_cell_04.png', 'creatures 04'),
  ShinraAsset('Créatures', 'assets/library/creatures_cell_05.png', 'creatures 05'),
  ShinraAsset('Créatures', 'assets/library/creatures_cell_06.png', 'creatures 06'),
  ShinraAsset('Créatures', 'assets/library/creatures_cell_07.png', 'creatures 07'),
  ShinraAsset('Créatures', 'assets/library/creatures_cell_08.png', 'creatures 08'),
  ShinraAsset('Créatures', 'assets/library/creatures_cell_09.png', 'creatures 09'),
  ShinraAsset('Créatures', 'assets/library/creatures_cell_10.png', 'creatures 10'),
  ShinraAsset('Créatures', 'assets/library/creatures_cell_11.png', 'creatures 11'),
  ShinraAsset('Créatures', 'assets/library/creatures_cell_12.png', 'creatures 12'),
  ShinraAsset('Créatures', 'assets/library/creatures_cell_13.png', 'creatures 13'),
  ShinraAsset('Créatures', 'assets/library/creatures_cell_14.png', 'creatures 14'),
  ShinraAsset('Créatures', 'assets/library/creatures_cell_15.png', 'creatures 15'),
  ShinraAsset('Créatures', 'assets/library/creatures_cell_16.png', 'creatures 16'),
  ShinraAsset('Créatures', 'assets/library/creatures_cell_17.png', 'creatures 17'),
  ShinraAsset('Créatures', 'assets/library/creatures_cell_18.png', 'creatures 18'),
  ShinraAsset('Créatures', 'assets/library/creatures_cell_19.png', 'creatures 19'),
  ShinraAsset('Créatures', 'assets/library/creatures_cell_20.png', 'creatures 20'),
  ShinraAsset('Véhicules', 'assets/library/vehicles.png', 'vehicles'),
  ShinraAsset('Véhicules', 'assets/library/vehicles_cell_01.png', 'vehicles 01'),
  ShinraAsset('Véhicules', 'assets/library/vehicles_cell_02.png', 'vehicles 02'),
  ShinraAsset('Véhicules', 'assets/library/vehicles_cell_03.png', 'vehicles 03'),
  ShinraAsset('Véhicules', 'assets/library/vehicles_cell_04.png', 'vehicles 04'),
  ShinraAsset('Véhicules', 'assets/library/vehicles_cell_05.png', 'vehicles 05'),
  ShinraAsset('Véhicules', 'assets/library/vehicles_cell_06.png', 'vehicles 06'),
  ShinraAsset('Véhicules', 'assets/library/vehicles_cell_07.png', 'vehicles 07'),
  ShinraAsset('Véhicules', 'assets/library/vehicles_cell_08.png', 'vehicles 08'),
  ShinraAsset('Véhicules', 'assets/library/vehicles_cell_09.png', 'vehicles 09'),
  ShinraAsset('Véhicules', 'assets/library/vehicles_cell_10.png', 'vehicles 10'),
  ShinraAsset('Véhicules', 'assets/library/vehicles_cell_11.png', 'vehicles 11'),
  ShinraAsset('Véhicules', 'assets/library/vehicles_cell_12.png', 'vehicles 12'),
  ShinraAsset('Véhicules', 'assets/library/vehicles_cell_13.png', 'vehicles 13'),
  ShinraAsset('Véhicules', 'assets/library/vehicles_cell_14.png', 'vehicles 14'),
  ShinraAsset('Véhicules', 'assets/library/vehicles_cell_15.png', 'vehicles 15'),
  ShinraAsset('Véhicules', 'assets/library/vehicles_cell_16.png', 'vehicles 16'),
  ShinraAsset('Fonds', 'assets/library/backgrounds.png', 'backgrounds'),
  ShinraAsset('Objets', 'assets/library/objects.png', 'objects'),
  ShinraAsset('Objets', 'assets/library/objects_cell_01.png', 'objects 01'),
  ShinraAsset('Objets', 'assets/library/objects_cell_02.png', 'objects 02'),
  ShinraAsset('Objets', 'assets/library/objects_cell_03.png', 'objects 03'),
  ShinraAsset('Objets', 'assets/library/objects_cell_04.png', 'objects 04'),
  ShinraAsset('Objets', 'assets/library/objects_cell_05.png', 'objects 05'),
  ShinraAsset('Objets', 'assets/library/objects_cell_06.png', 'objects 06'),
  ShinraAsset('Objets', 'assets/library/objects_cell_07.png', 'objects 07'),
  ShinraAsset('Objets', 'assets/library/objects_cell_08.png', 'objects 08'),
  ShinraAsset('Objets', 'assets/library/objects_cell_09.png', 'objects 09'),
  ShinraAsset('Objets', 'assets/library/objects_cell_10.png', 'objects 10'),
  ShinraAsset('Objets', 'assets/library/objects_cell_11.png', 'objects 11'),
  ShinraAsset('Objets', 'assets/library/objects_cell_12.png', 'objects 12'),
  ShinraAsset('Objets', 'assets/library/objects_cell_13.png', 'objects 13'),
  ShinraAsset('Objets', 'assets/library/objects_cell_14.png', 'objects 14'),
  ShinraAsset('Objets', 'assets/library/objects_cell_15.png', 'objects 15'),
  ShinraAsset('Objets', 'assets/library/objects_cell_16.png', 'objects 16'),
  ShinraAsset('Objets', 'assets/library/objects_cell_17.png', 'objects 17'),
  ShinraAsset('Objets', 'assets/library/objects_cell_18.png', 'objects 18'),
  ShinraAsset('Objets', 'assets/library/objects_cell_19.png', 'objects 19'),
  ShinraAsset('Objets', 'assets/library/objects_cell_20.png', 'objects 20'),
  ShinraAsset('Transformations', 'assets/library/transform_cell_01.png', 'transform 01'),
  ShinraAsset('Transformations', 'assets/library/transform_cell_02.png', 'transform 02'),
  ShinraAsset('Transformations', 'assets/library/transform_cell_03.png', 'transform 03'),
  ShinraAsset('Transformations', 'assets/library/transform_cell_04.png', 'transform 04'),
  ShinraAsset('Transformations', 'assets/library/transform_cell_05.png', 'transform 05'),
  ShinraAsset('Transformations', 'assets/library/transform_cell_06.png', 'transform 06'),
  ShinraAsset('Transformations', 'assets/library/transform_cell_07.png', 'transform 07'),
  ShinraAsset('Transformations', 'assets/library/transform_cell_08.png', 'transform 08'),
  ShinraAsset('Transformations', 'assets/library/transform_cell_09.png', 'transform 09'),
  ShinraAsset('Transformations', 'assets/library/transform_cell_10.png', 'transform 10'),
  ShinraAsset('Transformations', 'assets/library/transform_cell_11.png', 'transform 11'),
  ShinraAsset('Transformations', 'assets/library/transform_cell_12.png', 'transform 12'),
  ShinraAsset('Transformations', 'assets/library/transform_cell_13.png', 'transform 13'),
  ShinraAsset('Transformations', 'assets/library/transform_cell_14.png', 'transform 14'),
  ShinraAsset('Transformations', 'assets/library/transform_cell_15.png', 'transform 15'),
  ShinraAsset('Transformations', 'assets/library/transform_cell_16.png', 'transform 16'),
  ShinraAsset('Transformations', 'assets/library/transformations.png', 'transformations'),
  ShinraAsset('Univers', 'assets/library/univers.png', 'univers'),
  ShinraAsset('Univers', 'assets/library/universe_cell_01.png', 'universe 01'),
  ShinraAsset('Univers', 'assets/library/universe_cell_02.png', 'universe 02'),
  ShinraAsset('Univers', 'assets/library/universe_cell_03.png', 'universe 03'),
  ShinraAsset('Univers', 'assets/library/universe_cell_04.png', 'universe 04'),
  ShinraAsset('Univers', 'assets/library/universe_cell_05.png', 'universe 05'),
  ShinraAsset('Univers', 'assets/library/universe_cell_06.png', 'universe 06'),
  ShinraAsset('Univers', 'assets/library/universe_cell_07.png', 'universe 07'),
  ShinraAsset('Univers', 'assets/library/universe_cell_08.png', 'universe 08'),
  ShinraAsset('Univers', 'assets/library/universe_cell_09.png', 'universe 09'),
  ShinraAsset('Univers', 'assets/library/universe_cell_10.png', 'universe 10'),
  ShinraAsset('Univers', 'assets/library/universe_cell_11.png', 'universe 11'),
  ShinraAsset('Univers', 'assets/library/universe_cell_12.png', 'universe 12'),
  ShinraAsset('Univers', 'assets/library/universe_cell_13.png', 'universe 13'),
  ShinraAsset('Univers', 'assets/library/universe_cell_14.png', 'universe 14'),
  ShinraAsset('Univers', 'assets/library/universe_cell_15.png', 'universe 15'),
  ShinraAsset('Univers', 'assets/library/universe_cell_16.png', 'universe 16'),
  ShinraAsset('Univers', 'assets/library/universe_cell_17.png', 'universe 17'),
  ShinraAsset('Univers', 'assets/library/universe_cell_18.png', 'universe 18'),
  ShinraAsset('Univers', 'assets/library/universe_cell_19.png', 'universe 19'),
  ShinraAsset('Univers', 'assets/library/universe_cell_20.png', 'universe 20'),
];
